# Generated by Django 3.0 on 2020-04-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=200)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Gateway')),
            ],
        ),
    ]
